# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speed_limit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_limit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.IntegerField(default='0')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('ways', models.ManyToManyField(to='business_dashboard.Way')),
            ],
        ),
        migrations.AddField(
            model_name='way',
            name='waypoints',
            field=models.ManyToManyField(related_name='test', through='business_dashboard.Order', to='business_dashboard.Waypoint'),
        ),
        migrations.AddField(
            model_name='order',
            name='way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_dashboard.Way'),
        ),
        migrations.AddField(
            model_name='order',
            name='waypoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_dashboard.Waypoint'),
        ),
        migrations.AddField(
            model_name='business',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_dashboard.Waypoint'),
        ),
        migrations.AddField(
            model_name='business',
            name='street_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business_dashboard.Waypoint'),
        ),
    ]
