# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='WaypointOrder',
        ),
    ]
